// docs/chapter1/section2/src/1/ItemListList.vue
<!-- src/components/ItemList.vue -->
<script setup lang="ts">
import { ref } from 'vue'

interface Item {
  name: string
  price: number
}

const items = ref<Item[]>([
  { name: 'たまご', price: 100 },
  { name: 'りんご', price: 160 }
])
</script>

<template>
  <div>
    <div>ItemList</div>
    <ul><!-- [!code ++] -->
      <li v-for="item in items" :key="item.name"><!-- [!code ++] -->
        <div>名前: {{ item.name }}</div><!-- [!code ++] -->
        <div>{{ item.price }} 円</div><!-- [!code ++] -->
      </li><!-- [!code ++] -->
    </ul><!-- [!code ++] -->
  </div>
</template>

<style></style>

// docs/chapter1/dicts/react/src/1/ItemListList.tsx
import { useState } from 'react'

interface Item {
  name: string
  price: number
}

export default function ItemList() {
  const [items, setItems] = useState<Item[]>([
    { name: 'たまご', price: 100 },
    { name: 'りんご', price: 160 }
  ])

  return (
    <div>
      <div>ItemList</div>
      <div>
        {items.map((item) => (
          <div key={item.name}>
            <div className="name">名前：{item.name}</div>
            <div className="price">{item.price}円</div>
          </div>
        ))}
      </div>
    </div>
  )
}
