// docs/chapter1/section2/src/2/ItemListExpensive.vue
<template>
	<div>
		<div>ItemList</div>
		<ul>
			<li
				v-for="item in items"
				:key="item.name"
				:class="{ over500: item.price >= 500 }"
			>
				<div>名前: {{ item.name }}</div>
				<div>{{ item.price }} 円</div>
				<div v-if="item.price >= 10000">高額商品</div>
			</li>
		</ul>
		==略==
	</div>
</template>

// docs/chapter1/dicts/react/src/1/ItemListExpensive.tsx
import { useState } from 'react'
import styles from './ItemList.module.css'

interface Item {
  name: string
  price: number
}

export default function ItemList() {
  const [items, setItems] = useState<Item[]>([
    { name: 'たまご', price: 100 },
    { name: 'りんご', price: 160 }
  ])
  const [newItemName, setNewItemName] = useState('')
  const [newItemPrice, setNewItemPrice] = useState(0)

  const addItem = () => {
    setItems([...items, { name: newItemName, price: newItemPrice }])
  }

  return (
    <div>
      <div>ItemList</div>
      <div>
        {items.map((item) => (
          <div key={item.name} className={item.price >= 500 ? styles.over500 : undefined}>
            <div className="name">名前：{item.name}</div>
            <div className="price">{item.price}円</div>
            {item.price >= 10000 && <div>高額商品</div>}
          </div>
        ))}
      </div>
      <div>
        <label>
          名前
          <input onChange={(e) => setNewItemName(e.target.value)} type="text" value={newItemName} />
        </label>
        <label>
          価格
          <input
            onChange={(e) => setNewItemPrice(parseInt(e.target.value))}
            type="number"
            value={newItemPrice}
          />
        </label>
        <button onClick={addItem}>add</button>
      </div>
    </div>
  )
}
