// docs/chapter1/dicts/react/src/1/ItemListAdd.tsx
import { useState } from 'react'

interface Item {
  name: string
  price: number
}

export default function ItemList() {
  const [items, setItems] = useState<Item[]>([
    { name: 'たまご', price: 100 },
    { name: 'りんご', price: 160 }
  ])
  const [newItemName, setNewItemName] = useState('')
  const [newItemPrice, setNewItemPrice] = useState(0)

  const addItem = () => {
    setItems([...items, { name: newItemName, price: newItemPrice }])
  }

  return (
    <div>
      <div>ItemList</div>
      <div>
        {items.map((item) => (
          <div key={item.name}>
            <div className="name">名前：{item.name}</div>
            <div className="price">{item.price}円</div>
          </div>
        ))}
      </div>
      <div>
        <label>
          名前
          <input onChange={(e) => setNewItemName(e.target.value)} type="text" value={newItemName} />
        </label>
        <label>
          価格
          <input
            onChange={(e) => setNewItemPrice(parseInt(e.target.value))}
            type="number"
            value={newItemPrice}
          />
        </label>
        <button onClick={addItem}>add</button>
      </div>
    </div>
  )
}

// docs/chapter1/section2/src/2/ItemListAdd.vue
<script setup lang="ts">
import { ref } from 'vue'

interface Item {
  name: string
  price: number
}

const items = ref<Item[]>([
  { name: 'たまご', price: 100 },
  { name: 'りんご', price: 160 }
])
const newItemName = ref('')
const newItemPrice = ref(0)

const addItem = () => {
  items.value.push({ name: newItemName.value, price: newItemPrice.value })
}
</script>

<template>
  <div>
    <div>ItemList</div>
    <ul>
      <li v-for="item in items" :key="item.name">
        <div>名前: {{ item.name }}</div>
        <div>{{ item.price }} 円</div>
      </li>
    </ul>
    <div>
      <label>
        名前
        <input v-model="newItemName" type="text" />
      </label>
      <label>
        価格
        <input v-model="newItemPrice" type="number" />
      </label>
      <button @click="addItem">追加</button>
    </div>
  </div>
</template>

<style></style>
